# Generated by Django 3.1.5 on 2021-01-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('AddressLine1', models.CharField(max_length=100)),
                ('AddressLine2', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100)),
                ('rack_No', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.category')),
                ('manufacturer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='productPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.productdetails')),
            ],
        ),
    ]
